### PR TITLE
Added the german actions pack for DBM Beta

### PR DESCRIPTION
**Pull request by ZockerNico**
Those are all current beta actions of DBM. Every single action has been translated by me into german (which also includes the action names).

### CODE REVIEW

**Comment by LasseNiermann** [comment]
Thank you very, very, very much. :D

**Comment by SeikiMatt** [comment]
Have you checked if your changes to the actions cause any problems or conflicts with DBM?
I'm pretty sure it shouldn't but it's still better to ask.

**Comment by ZockerNico** [comment]
Hey SeikiMatt! I'm pretty sure they're all working fine. I've just added that comment in README.md to make sure that the action NAMES have been changed and the progress in your bot can be lost because of that. People could be sad that all actions are "unknown" after they updated the actions. They don't break the bot itself but it can cause problems with their already made commands / events. So it would be better if you start a new project after you installed that modpack. ;-)

**Comment by SeikiMatt** [comment]
Fair enough. Thank you very much for the contribution, merging now.

**Comment by Almeeida** [comment]
@ZockerNico You should probably add it to the [main readme](https://github.com/Discord-Bot-Maker-Mods/DBM-Translations/blob/master/Readme.md)

**Pull request merged**
